[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable optimizer with 200 runs
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Network configurations
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

# Etherscan API keys for verification
[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Deployment configuration for Base Sepolia
[profile.deploy]
# Use the same settings as default plus deployment-specific overrides
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
# Use the base-sepolia network
chain_id = 84532
